import datetime
print(datetime.datetime.now())
print('-'*20)
print(datetime.datetime.now().year)
print('-'*20)
print(datetime.datetime.now().month)
print('-'*20)
print(datetime.datetime.now().day)
print('-'*20)
print(datetime.datetime.min)
print('-'*20)
print(datetime.datetime.max)
print('-'*20)
# time only
print(datetime.datetime.now().time())
print('-'*20)
print(datetime.datetime.now().time().hour)
print('-'*20)
print(datetime.datetime.now().time().minute)
print('-'*20)
print(datetime.datetime.now().time().second)
print('-'*20)
print(datetime.time.min)
print('-'*20)
print(datetime.time.max)
print('-'*20)
print(datetime.datetime(2004, 1, 1))
print('-'*20)
past = datetime.datetime(2004, 1, 1)
now = (datetime.datetime.now())
print(now - past)
print('-'*20)
print(past.strftime("%A"))  # Python strftime reference cheatsheet
